// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWQtRFuwCuRv2QxFRYNxrR9mSKZQ9EB_8',
    appId: '1:366809458395:web:080cb21cbcfe5d06f84efe',
    messagingSenderId: '366809458395',
    projectId: 'plomero-express',
    authDomain: 'plomero-express.firebaseapp.com',
    storageBucket: 'plomero-express.firebasestorage.app',
    measurementId: 'G-DGW917H7D6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSj2onfCAh8ZIiLTGNltVXcTzgOihUkd8',
    appId: '1:366809458395:android:f56cfe13393a8dfdf84efe',
    messagingSenderId: '366809458395',
    projectId: 'plomero-express',
    storageBucket: 'plomero-express.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9LSvg-JrFWfsjkRw8LxMbcYkfaUKif2M',
    appId: '1:366809458395:ios:54e2dfc93ce97970f84efe',
    messagingSenderId: '366809458395',
    projectId: 'plomero-express',
    storageBucket: 'plomero-express.firebasestorage.app',
    androidClientId: '366809458395-c5s1epi93647ebidcsmgtgdj55ofv613.apps.googleusercontent.com',
    iosClientId: '366809458395-t09nrp45321pctl1abc6ou4lg1gf3p5c.apps.googleusercontent.com',
    iosBundleId: 'com.example.plomeroExpress',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9LSvg-JrFWfsjkRw8LxMbcYkfaUKif2M',
    appId: '1:366809458395:ios:54e2dfc93ce97970f84efe',
    messagingSenderId: '366809458395',
    projectId: 'plomero-express',
    storageBucket: 'plomero-express.firebasestorage.app',
    androidClientId: '366809458395-c5s1epi93647ebidcsmgtgdj55ofv613.apps.googleusercontent.com',
    iosClientId: '366809458395-t09nrp45321pctl1abc6ou4lg1gf3p5c.apps.googleusercontent.com',
    iosBundleId: 'com.example.plomeroExpress',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWQtRFuwCuRv2QxFRYNxrR9mSKZQ9EB_8',
    appId: '1:366809458395:web:01c051a60980eb11f84efe',
    messagingSenderId: '366809458395',
    projectId: 'plomero-express',
    authDomain: 'plomero-express.firebaseapp.com',
    storageBucket: 'plomero-express.firebasestorage.app',
    measurementId: 'G-JFCP8GTE46',
  );
}
